port 443
proto tcp
dev tun
ca /openvpn-ca/pki/ca.crt
cert /openvpn-ca/pki/issued/server.crt
key /openvpn-ca/pki/private/server.key
dh /openvpn-ca/pki/dh.pem
server 10.8.0.0 255.255.255.0
push "redirect-gateway def1"
push "dhcp-option DNS 8.8.8.8"
keepalive 10 120
cipher AES-256-GCM
topology subnet
user nobody
group nogroup
persist-key
persist-tun
status openvpn-status.log
verb 3
